[package]
name = "atlas-core"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
automerge = "0.10"
ciborium = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { version = "1.24.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.27.0"
